name: audytor_app
description: Aplikacja Audytor do wykonywania audytów i raportów PDF.
publish_to: 'none'
version: 0.8.8+21
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  image: ^4.5.4
  intl: ^0.20.2
  pdf: ^3.11.3
  printing: ^5.14.2
  archive: ^4.0.7
  file_picker: ^8.3.7
  share_plus: ^10.1.4
  cross_file: ^0.3.4+2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
